#!/usr/bin/env python3

import sys
import re


def invalid_filename(filename):
    pattern = r"^[a-zA-Z0-9][a-zA-Z0-9._-]*$"
    if re.match(pattern, filename) is None:
        return True
    return False
